### ISSUE TITLE
Same code saved multiple times.

### ISSUE THREAD

**Issue by flaredragon** [coding-blocks/ide#126]
The Same code when saved multiple times gets saved at different URL's - 
<ul>
<li>https://codingblocks.com/ide/#/s/1855</li>
<li>https://codingblocks.com/ide/#/s/1856</li>
<li>https://codingblocks.com/ide/#/s/1857</li>
</ul>

This feature Can be enhanced by Adding and Edit Request on clicking Save Option(like ideone) instead of saving the code again and again at Multiple URLs and wasting resources.

**Comment by abhishek97** [comment]
We should definitely go for this.
do you want to work on it @flaredragon ?

**Comment by flaredragon** [comment]
Thanks but I'm not so experienced in Vue.js will take up other JavaScript issues :)

**Comment by flaredragon** [comment]
@abhishek97 I was really curious enough to work on it.
Basically, I have done the job it checks from the open URL and compares the codes
If they are same it won't save it again.
Otherwise, it gets saved at a new place.
Should I make a PR or you'll like the code first?

**Comment by abhishek97** [comment]
@flaredragon I am happy to see made some efforts. Thank you. I've added some review to your pr, please make these minor changes so that we can merge it. 

Also, one enhancement over your current strategy can be to compare the hash of the codes instead of the codes themselves. The entire code can be pretty large and be storing an extra copy of it, just to compare them might not be the best option. In a nutshell,

- `Store checkData = SHA(code)`
- ` if ( checkData === SHA(currentCode) ) { // don't save }`

**Comment by flaredragon** [comment]
Right I never thought of it in this way.Great Approach!
